name: notetaking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animated_switcher_plus: ^1.0.3
  awesome_snackbar_content: ^0.1.0
  cloud_firestore: ^4.4.2
  cloud_firestore_web: ^3.3.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.6
  firebase_core: ^2.6.1
  firebase_crashlytics: ^3.0.13
  firebase_ui_auth: ^1.1.11
  firebase_ui_firestore: ^1.2.5
  firebase_ui_oauth_google: ^1.0.18
  firestore_ui: ^1.25.1
  flex_color_picker: ^3.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.17
  get: ^4.6.5
  get_storage: ^2.0.3
  google_mobile_ads: ^2.3.0
  google_sign_in: ^5.4.4
  iconswitcher: ^2.0.2
  intl: ^0.17.0
  motion: ^1.3.3
  slide_switcher: ^1.1.2
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.0

flutter:
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  assets:
    - dotenv
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon_launcher/mipmap-xxxhdpi/ic_launcher.png
  color_dark: "#121212"
  android_12: null

icons_launcher:
  image_path: "assets/icon_launcher/icons8-note-64.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
